Repository dusk-network/piecrust, pull requests merged in 2022-10, with the labels that each got.

#98 Session Commits Persistence Implementation
  .github/workflows/build.yml
  docs/on-disk-datastore.md
  rust-toolchain
  vmx/src/commit.rs
  vmx/src/vm.rs
  vmx/tests/persistence.rs
Labels: team:Core, type:feature

#90 Add module metering
  .github/workflows/build.yml
  rust-toolchain
  uplink/src/state.rs
  vmx/Cargo.toml
  vmx/src/error.rs
  vmx/src/imports.rs
  vmx/src/instance.rs
  vmx/src/module.rs
  vmx/src/session.rs
  vmx/src/vm.rs
  vmx/tests/debug.rs
  vmx/tests/points.rs
Labels: team:Core, type:feature

#104 Add host metadata support
  modules/everest/src/lib.rs
  uplink/src/lib.rs
  uplink/src/state.rs
  vmx/Cargo.toml
  vmx/src/error.rs
  vmx/src/imports.rs
  vmx/src/instance.rs
  vmx/src/session.rs
  vmx/tests/height.rs
Labels: team:Core, type:feature

#105 Add benchmark and reduce push-pops in test
  modules/stack/Cargo.toml
  vmx/Cargo.toml
  vmx/benches/stack.rs
  vmx/tests/stacked.rs
Labels: mark:next, status:minor, team:Core

#110 Add `from_bytes` and `to_bytes` for `ModuleId`
  piecrust-uplink/src/types.rs
Labels: team:Core, type:feature

#109 Implemented deploy_with_id
  piecrust/src/vm.rs
  piecrust/tests/deploy_with_id.rs
Labels: mark:next
