Repository dusk-network/piecrust, pull requests merged in 2022-08, with the labels that each got.

#14 Make `self_id` available to contracts
  Cargo.toml
  dallo/src/lib.rs
  dallo/src/ops.rs
  hatchery/src/instance.rs
  hatchery/src/world.rs
  hatchery/tests/callcenter.rs
  modules/box/src/lib.rs
  modules/callcenter/src/lib.rs
  modules/counter/src/lib.rs
  modules/fibonacci/src/lib.rs
  modules/stack/src/lib.rs
  modules/vector/src/lib.rs
Labels: team:Core, type:feature

#28 Introduce event system
  dallo/src/state.rs
  hatchery/src/lib.rs
  hatchery/src/world.rs
  hatchery/src/world/event.rs
  hatchery/tests/boxen.rs
  hatchery/tests/callcenter.rs
  hatchery/tests/counter.rs
  hatchery/tests/events.rs
  hatchery/tests/fibonacci.rs
  hatchery/tests/stacked.rs
  hatchery/tests/vector.rs
  modules/Cargo.toml
  modules/callcenter/src/lib.rs
  modules/counter/src/lib.rs
  modules/eventer/Cargo.toml
  modules/eventer/src/lib.rs
Labels: team:Core, type:feature

#31 Add `caller` host function
  dallo/src/state.rs
  dallo/src/types.rs
  hatchery/src/instance.rs
  hatchery/src/world.rs
  hatchery/src/world/stack.rs
  hatchery/tests/callcenter.rs
  modules/callcenter/src/lib.rs
Labels: team:Core, type:feature

#34 Add `height` host call
  dallo/src/state.rs
  hatchery/src/world.rs
  hatchery/src/world/stack.rs
  hatchery/tests/height.rs
  modules/Cargo.toml
  modules/everest/Cargo.toml
  modules/everest/src/lib.rs
Labels: team:Core, type:feature

#36 Add module metering
  hatchery/Cargo.toml
  hatchery/src/error.rs
  hatchery/src/instance.rs
  hatchery/src/world.rs
  hatchery/src/world/event.rs
  hatchery/src/world/store.rs
  hatchery/tests/points.rs
Labels: team:Core, type:feature

#45 Move the argument buffer handlnig to `dallo`
  dallo/src/helpers.rs
  dallo/src/lib.rs
  dallo/src/state.rs
  hatchery/src/instance.rs
  hatchery/src/world.rs
  hatchery/tests/self_snapshot.rs
  modules/box/src/lib.rs
  modules/callcenter/src/lib.rs
  modules/counter/src/lib.rs
  modules/eventer/src/lib.rs
  modules/everest/src/lib.rs
  modules/fibonacci/src/lib.rs
  modules/self_snapshot/src/lib.rs
  modules/stack/src/lib.rs
  modules/vector/src/lib.rs
Labels: mark:next, team:Core, type:feature

#47 Add `spent` and `limit` host calls
  dallo/src/lib.rs
  dallo/src/state.rs
  hatchery/src/world.rs
  hatchery/src/world/event.rs
  hatchery/src/world/stack.rs
  hatchery/tests/points.rs
  modules/Cargo.toml
  modules/spender/Cargo.toml
  modules/spender/src/lib.rs
Labels: team:Core, type:feature

#51 Add host module support
  dallo/src/lib.rs
  dallo/src/state.rs
  hatchery/src/lib.rs
  hatchery/src/world.rs
  hatchery/src/world/native.rs
  hatchery/tests/host.rs
  modules/Cargo.toml
  modules/host/Cargo.toml
  modules/host/src/lib.rs
Labels: team:Core, type:feature

#17 Run CI on self-hosted runner
  .github/workflows/build.yml
Labels: team:Core, type:enhancement
