Repository dusk-network/piecrust, pull requests merged in 2023-01, with the labels that each got.

#133 Add `from_bytes` and `to_bytes` to commit IDs
  piecrust/src/commit.rs
Labels: team:Core, type:enhancement

#137 Make `transact` and `query` take arguments by reference
  README.md
  modules/callcenter/src/lib.rs
  modules/self_snapshot/src/lib.rs
  modules/spender/src/lib.rs
  piecrust-uplink/src/state.rs
  piecrust/src/instance.rs
  piecrust/src/session.rs
  piecrust/tests/box.rs
  piecrust/tests/callcenter.rs
  piecrust/tests/cold-reboot/src/main.rs
  piecrust/tests/counter.rs
  piecrust/tests/debug.rs
  piecrust/tests/deploy_with_id.rs
  piecrust/tests/events.rs
  piecrust/tests/fallible.rs
  piecrust/tests/fibonacci.rs
  piecrust/tests/height.rs
  piecrust/tests/host.rs
  piecrust/tests/persistence.rs
  piecrust/tests/points.rs
  piecrust/tests/self_snapshot.rs
  piecrust/tests/session_commit.rs
  piecrust/tests/stacked.rs
  piecrust/tests/vector.rs
Labels: team:Core, type:enhancement

#134 Error Infrastructure Enhancement
  piecrust/Cargo.toml
  piecrust/src/error.rs
Labels: mark:next

#143 Rename module tests
  modules/Cargo.toml
  modules/crossover/Cargo.toml
  modules/crossover/src/lib.rs
  piecrust/tests/crossover.rs
  piecrust/tests/debugger.rs
  piecrust/tests/eventer.rs
  piecrust/tests/everest.rs
  piecrust/tests/fallible_counter.rs
  piecrust/tests/spender.rs
  piecrust/tests/stack.rs
Labels: mark:next, team:Core
