Repository dusk-network/piecrust, pull requests merged in 2023-04, with the labels that each got.

#188 Lock `wasmer` to version `3.1`
  piecrust/Cargo.toml
Labels: team:Core

#140 Add crate level documentation for `piecrust-uplink::types`
  piecrust-uplink/src/types.rs
Labels: mark:next, team:Core, type:docs

#198 Add example merkle tree module
  modules/Cargo.toml
  modules/README.md
  modules/merkle/Cargo.toml
  modules/merkle/src/lib.rs
  piecrust/tests/merkle.rs
Labels: team:Core, type:enhancement
